version: 2

updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - dragoszt
  assignees:
  - dragoszt
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.1
    - 1.9.0
  - dependency-name: rubocop-performance
    versions:
    - 1.10.0
    - 1.10.2
  - dependency-name: codecov
    versions:
    - 0.4.3
    - 0.5.0
  - dependency-name: webmock
    versions:
    - 3.11.1
    - 3.11.3
    - 3.12.0
  - dependency-name: activerecord
    versions:
    - 6.1.2.1
  - dependency-name: timecop
    versions:
    - 0.9.2
    - 0.9.3
    - 0.9.4
  - dependency-name: rails
    versions:
    - 6.1.2
  - dependency-name: jwt
    versions:
    - 2.2.2
  - dependency-name: actionpack
    versions:
    - 6.1.1
  - dependency-name: nokogiri
    versions:
    - 1.11.1
